language: julia
os:
  - linux
  - osx
julia:
  - "0.7"
  - "1.0"
  - "nightly"
env:
  - PYTHON=   # Always use Conda
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)';
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'using Pkg; ;gcd(Pkg.dir("ASDF")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
